name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file docker/server/Dockerfile --tag hashkeyhub/conductor-server:$git_hash
